services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vrchatgram
      MYSQL_USER: vrchatgram
      MYSQL_PASSWORD: vrcss
    ports:
      - 3300:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    command: --default-authentication-plugin=mysql_native_password
  nextjs:
    container_name: nextjs
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./nextjs
        target: /app
      - type: bind
        source: ./nextjs/node_modules
        target: /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm i && npx prisma db push --force-reset && npm run seed && npm run dev"
    restart: always
    tty: true
    stdin_open: true
    networks:
      - mynetwork
volumes:
  node_modules:
  mysql-data:
networks:
  mynetwork:
    external: true