services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - type: bind
        source: ./front
        target: /app
      - type: bind
        source: ./front/node_modules
        target: /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm i && npm run dev"
    restart: always
    tty: true
    stdin_open: true
volumes:
  node_modules: