// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	DATABASE_URL: string;
	DIRECT_URL: string;
	NEXT_PUBLIC_API_KEY: string;
	NEXT_PUBLIC_AUTH_DOMAIN: string;
	NEXT_PUBLIC_PROJECT_ID: string;
	NEXT_PUBLIC_STORAGE_BUCKET: string;
	NEXT_PUBLIC_MESSAGING_SENDER_ID: string;
	NEXT_PUBLIC_APP_ID: string;
	NEXT_PUBLIC_MEASUREMENT_ID: string;
	NEXTAUTH_SECRET: string;
}
